OOP school library: refactor your code
Tamunokuro/Ruby-OOP-school-library pull request #5
Opened 2023-02-20 15:12 UTC by SSEKPIUS

> Pay special attention to the "Single-responsibility Principle".

Make sure that the role of main.rb is only to start your code and ask the user for the initial choice of options (or to quit).
Extract some pieces of logic into separate class(es).

2023-02-20 15:41 UTC, danmainah requested changes
Hi @SSEKPIUS and @Tamunokuro , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

✔️ No linter errors
✔️ Gitflow was correctly used



# Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-02-20 15:41 UTC, danmainah commented on app.rb
>    end
- [ ] @SSEKPIUS and @Tamunokuro kindly ensure all requests for input and input validation should be placed in the main.rb file and/or classes/methods whose responsibilities are to request or validate input

2023-02-20 15:41 UTC, danmainah commented on app.rb
>    end
- [ ] @team also ensure your methods are following `Single responsibility rule` ,eg the create person method should have a statement to create student and teacher, the create student and create teacher method should be called in create person method to pass specialized parameter  unique to teachers and students

2023-02-21 11:51 UTC, TedLivist approved these changes
## STATUS: APPROVED ✔️ ✔️

Hi @SSEKPIUS and @Tamunokuro,

✔️ Implementation of SOLID principles

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-21 12:23 UTC, merged